INSERT INTO product_type_table (id, type) values (1, 'pieczywo');
INSERT INTO product_type_table (id, type) values (2, 'mięso');
INSERT INTO product_type_table (id, type) values (3, 'nabiał');
INSERT INTO product_type_table (id, type) values (4, 'owoce');

INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Ziemniaki krajowe młode', 4,  5.49, 'kg.', 'Ziemniaki niemyte. Bogate w skrobię oraz stanowią nieodzowny składnik diety. Szybkie i łatwe w przygotowaniu. Kaliber powyżej 35mm średnicy.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Kalafior', 4, 6.99, 'kg.', 'Kalafior początkowo popularny był wyłącznie na Cyprze, skąd pochodzi, jednak bardzo szybko zaczął stawać się wykorzystywany w innych częściach świata. Do Polski trafił dopiero w XVI wieku, jednak od tamtego czasu zyskał sobie ogromną przychylność wielu pasjonatów gotowania. Wykorzystuje się go obecnie całkiem powszechnie jako składnik zup, sałatek oraz wielu rozmaitych potraw. Idealnie komponuje się z innymi warzywami, chociażby z marchewką czy groszkiem, dzięki czemu często stanowi nawet jeden z podstawowych dodatków do dań głównych, goszczących podczas obiadu. ');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Bób', 4, 35.99 , 'kg.', 'Bób jest jednoroczną rośliną strączkową, która swój czas ma zawsze w porze letniej. Jej owoce to sporych rozmiarów strąki, w których kryje się od 2 do 5 nerkowatych nasion, zwanych właśnie bobem. Najczęściej mają one kolor jasnozielony lub bladożółty i to właśnie te nasiona są prawdziwym przysmakiem podczas letnich kolacji. Po ugotowaniu smakują naprawdę rewelacyjnie. Trzeba pamiętać aby wodę, w której ma się gotować bób zawsze posolić i dodać odrobinę masła dla lepszego smaku. Z bobu można również zrobić zupę, czy dodać go do sałatek. Specjaliści od zdrowego żywienia cenią go za dużą ilość białka, błonnika, węglowodanów, tłuszczów oraz witamin: B1, B2, PP, C i A.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Papryka żółta', 4, 15.99, 'kg.', 'Żółta papryka znana jest przede wszystkim jako znakomite źródło wielu witamin i cennych składników mineralnych. Zawiera ona przede wszystkim spore ilości witamin z grupy B, a także wapnia, potasu, żelaza i magnezu. Charakteryzuje się znakomitymi właściwościami poprawiającymi wzrok oraz ogólne samopoczucie. Dzięki swojemu intensywnemu kolorowi może ona być wykorzystywana nie tylko jako jeden z podstawowych składników posiłków, lecz także jako atrakcyjny dodatek, potrafiący bez najmniejszych trudności dodać uroku każdej przygotowywanej sałatce, surówce czy wielu przystawkom.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Cykoria żółta', 4, 7.49, 'kg.', 'Cykoria żółta krajowa poza swoimi naturalnymi walorami estetycznymi charakteryzuje się pewną wyczuwalną w smaku goryczką, która ożywia jej smak. Cykoria stanowi idealne dopełnienie kompozycji warzywnych. Ze względu na swoje wyjątkowe walory smakowe i odżywcze cykoria należy do produktów bardzo szybko rozchwytywanych. Na rynkach spożywczych jest ona dostępna przeważnie w listopadzie, grudniu, styczniu, lutym, marcu oraz kwietniu, czyli w okresie, gdy brakuje większości świeżych warzyw. Jest ona bogatym źródłem witamin i minerałów, do których zaliczyć można chociażby takie jak: sód, potas, magnez, mangan, żelazo, miedź, cynk, fosfor, chlor oraz karoten.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Natur Jogurt naturalny', 3, 1.19, 'szt.', 'Jogurt naturalny Zott, o zawartości tłuszczu nieprzekraczającej 3%, to idealny składnik wielu potraw i przekąsek. Może być dodawany do sałatek, sosów i surówek. Świetnie smakuje z owocami, warzywami, musli. Jogurt został wyprodukowany w sposób odpowiadający wszystkim obowiązującym normom, przy wykorzystaniu najwyższej klasy technologii, dzięki czemu mogą Państwo cieszyć się jego niepowtarzalnym, naturalnym smakiem.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Ser Camembert naturalny', 3, 4.99, 'szt.', 'Ser Camembert President to jeden z najsłynniejszych gatunków sera pleśniowego rodem z Francji. Delikatna, miękka struktura, kremowe wnętrze i delikatność smaku, sprawiają, że niemal rozpływa się w ustach. Stanowi on idealną kompozycję z czerwonym winem, doda również smaku każdej kanapce, zarówno samodzielnie, jak również w towarzystwie innych składników. Wraz z kurczakiem z grilla, sałatką i papryczkami bądź pomidorem – stworzy pyszny posiłek na śniadanie, podwieczorek, ale także do pracy, czy szkoły. Ser Camembert równie smaczny będzie jako składnik sałatki, dodatek do warzyw grillowanych albo tostów z kurczakiem.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Wiejski Serek twarogowy', 3, 1.79, 'szt.', 'Serek twarogowy ziarnisty ze śmietanką.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Jogurt siemię lniane śliwka', 3, 2.99, 'szt.', 'Jogurt o smaku śliwki ze zbożami (0,38%) i siemieniem lnianym (0,18%) oraz szczepem bakterii ActiRegularis .');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Ser kozi plastry z rozmarynem', 3, 9.99, 'szt.', 'Holenderski ser kozi o kremowej konsystencji i łagodnym smaku, który został przełamany dodatkiem aromatycznego rozmarynu.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Pasztetowa z borowikiem bezglutenowa', 2, 8.79, 'szt.', 'Pasztetowa z borowikiem przyprawiona naturalnie. ');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Filet z piersi z kurczaka', 2, 16.99, 'kg.', 'Najwyższej jakości filet klasy A stanowi idealne źródło wartości odżywczych i białka. Dzięki swojej łatwej w przygotowaniu formie znajduje zastosowanie w wielu rodzajach kuchni. Filet to idealna podstawa diety osób aktywnych fizycznie.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Stek z antrykotu', 2, 100, 'kg.', 'Stek z antrykotu z selekcjonowanej, polskiej wołowiny dojrzewającej marki TENDER. Pakowany próżoniowo, z młodego bydła ras mięsnych, dojrzewający minimum 14 dni. Stek idealnie nadaje się do smażenia i grillowania. Sugerowany poziom wysmażenia medium-rare. Wyjątkową kruchość i delikatność mięsa gwarantuje krajowy system jakości mięsa wołowego Quality Meat Program (QMP)');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Szponder wołowy z kością', 2, 30.99, 'kg.', 'Szponder wołowy z kością, bez skóry to dolna część żeberek o ciemnoczerwonej barwie i niewielkim przeroście tłuszczowym. Posiada bogate walory smakowe oraz daje wiele możliwości kulinarnych.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Wątróbka z indyka', 2, 12.99, 'kg.', 'Mięso indyka słynie ze swoich walorów zdrowotnych i smakowych. Mięso indycze, w porównaniu z wieprzowiną czy wołowiną, odznacza się lepszymi właściwościami smakowo-zapachowymi i dietetycznymi. Tłuszcz zawarty w mięsie indyka jest lżej strawny i łatwiej przyswajalny. Co bardzo ważne, zawiera więcej nienasyconych kwasów tłuszczowych, niezbędnych w diecie człowieka. Spośród wszystkich gatunków drobiu to właśnie indyk zawiera najwięcej cennych wielonienasyconych kwasów tłuszczowych (PUFA).');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Chleb chłopski', 1, 5.70, 'szt.', ' Chleb pszenno- żytni wypiekany na naturalnym zakwasie żytnim. Jeden z najczęściej wybieranych chlebów w naszej piekarni, doceniany za swoją uniwersalność i tradycyjny smak. Dzięki dużej ilości kwasu żytniego chleb utrzymuje świeżość na długo. Sprawdzi się idealnie na święta czy dłuższe weekendy  ');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Chleb żytni z jagodami goji', 1, 10, 'szt.', 'Chleb wypiekany w 100% z mąki żytniej, na naturalnym zakwasie. Wyróżnia go dodatek jagód goji znanych ze swoich prozdrowotnych właściwości. Poprawiają odporność, wpływają korzystnie na pracę serca oraz poziom cukru i cholesterolu we krwi. Chleb zawiera ciemne kiełki żytnie oraz nasiona ostropestu plamistego, który wspomaga trawienie. Dodatek soku jabłkowego nadaje mu przyjemnego aromatu i sprawia, że chleb dłużej zachowuje świeżość.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Żytnie Pieczywo lekkie', 1, 4.99, 'szt.', 'Pieczywo lekkie żytnie WASA idealnie nadaje się na pierwsze śniadanie. Dostarczy energii na cały dzień i jednocześnie porcji potrzebnych organizmowi witamin i minerałów. Doskonała alternatywa dla tuczącego, białego pieczywa. Aby wzbogacić jego smak wystarczy dodać ulubione dodatki, np. wędlinę, ser, warzywa czy łososia. Regularne jedzenie tego pieczywa lekkiego jest zalecane w przypadku stosowania diet odchudzających. A gdy dopadnie nas w ciągu dnia mały głód, wówczas także można przegryźć sobie to pieczywo. Wówczas mamy pewność, że nasza figura zawsze będzie zgrabna i powabna.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Chałka', 1, 5.99, 'szt.', 'Ta chałka wypiekana jest w oparciu o tradycyjną recepturę znaną od wielu lat, wyłącznie przy wykorzystaniu naturalnych składników. Unikalny, lekko słodki smak zawdzięcza delikatnej posypce z prawdziwej kruszonki. Wykonany z najwyższej klasy drożdżowego ciasta warkocz będzie doskonałym dodatkiem do kubka kakao, przekąską podczas przerwy w pracy, czy szkole, a dodatkowo dobrze sprawdzi się podczas tradycyjnej kolacji wigilijnej. Przy wypieku chałki, piekarnie Putka nie stosują chemicznych polepszaczy smaku ani konsystencji, jednocześnie gwarantując długą trwałość pieczywa.');
INSERT INTO product_table (name, type_id, price, measureType, description) VALUES ('Bułka grahamka', 1, 0.90, 'szt.', 'Bułka pszenno-żytnia z dodatkiem otrąb pszennych, ziaren żyta, płatków owsianych, ziaren słonecznika i siemienia lnianego. Będzie to zdrowa i pożywna baza do zdrowych kanapek. Idealna na śniadanie lub lunch. ');




